@echo off
echo Cleaning up previous sessions...
taskkill /F /IM python.exe /T >nul 2>&1
echo.
echo Starting DentalPilot on C: Drive...
echo Please wait about 60 seconds for the AI model to load...
"C:/Program Files/Python312/python.exe" "c:\Users\HP\Downloads\Deep-Learning-Model-for-Dental-Image-Classification-main\Deep-Learning-Model-for-Dental-Image-Classification-main\app.py"
pause
